### ISSUE TITLE
Native pipewire as sound server ?

### ISSUE THREAD

**Issue by chromer030** [An7ar35/ctune#25]
Thanks for tool , please add pipewire native server.

**Comment by An7ar35** [comment]
It's planned. I will probably not be for the next major release but likely for one soon after that time allowing :crossed_fingers: .

**Comment by An7ar35** [comment]
Added a basic implementation in v1.3.0

to enable either in the config:
```
IO::Plugin::SoundServer=pipewire
```

or in ctune directly:
```
Options menu > Configuration > Plugins > Sound Servers > pipewire
```
