### ISSUE TITLE
resizing Konsole window leads to core dump

### ISSUE THREAD

**Issue by antbricks** [An7ar35/ctune#26]
While running, grab a corner of the Konsole window (running in Arch, btw ;) and resize. I get the following:

double free or corruption (out)
Aborted (core dumped)

Let me know if you want me to grab a file or run with --debug or anything.
Thanks for the cool tool!

**Comment by An7ar35** [comment]
Thanks for the bug report. :+1: 

I'm going to need:
- log (`--debug`),
- what player and sound server combo you were using at the time,
- was a station playing at the time and,
- what widgets were opened (basically the UI state just before you resized - screenshot would do here)

That should help me narrow down where things went sideways.

**Comment by antbricks** [comment]
I can recreate the issue without actually streaming any audio. i.e. just start ctune, and at the 'favorites' screen I just resize and get a crash. It happens pretty reliably, but not every resize crashes (see successful resize screencap).
It's ctune 1.2.0, using ffmpeg on Arch+PulseAudio, but since I can crash without starting audio, it seems like a windowing issue.

![ctune_resize_crash](https://user-images.githubusercontent.com/38120752/220943796-4d063aa7-f095-4074-8338-bd1311d6a449.jpg)
![ctune_successfully_resized](https://user-images.githubusercontent.com/38120752/220943798-ba1c6287-eb6c-4b90-99fb-34d97213c1ae.jpg)
![screenshot_pre-crash](https://user-images.githubusercontent.com/38120752/220943802-af925fe9-c066-41b8-8acc-eee838fc19af.png)
[ctune_resize_segfault.log](https://github.com/An7ar35/ctune/files/10814898/ctune_resize_segfault.log)

**Comment by An7ar35** [comment]
Thanks for all that, it helped narrow down the scope. After drilling into it it looks like a race condition is happening between UI callbacks and the resize calls. Once I make sure and it is the case, I should have a fix with the next update.

**Comment by An7ar35** [comment]
Should be corrected now in v1.3.0
