### ISSUE TITLE
Fail to load api for stations

### ISSUE THREAD

**Issue by angelosne** [An7ar35/ctune#28]
**1. Basic information**
***1.1 System information***
- **Terminal/Shell:** e.g.: Konsole 21.04 using BASH 5.1.8
- Console 46 (GNOME)
- **Distro:**
- Endeavouros
- **Kernel:**
- 6.6.38-1-lts

***1.2 cTune version***
```
ctune v1.2.0
====================================================
Copyright .....: 2020-23 E.A.Davison (eadavison.com)
Released under : AGPL3
----------------------------------------------------
Libraries:
  FFMpeg (libavformat 61.1.100, libavcodec 61.3.100, libswresample 5.1.100)
  PulseAudio (17.0.0)
  SDL (2.30.5)
  ALSA (1.2.12)
  json-c 0.17.99
  OpenSSL 3.3.1 4 Jun 2024
  Curl 8.8.0
  nCurses 6.5.20240427
```

**2. Describe the bug**
When I hit any category in browser or search for any station it returns
fetch failed - see log

**3. To Reproduce**
Any time I try to load any category

**4. Expected behavior**
Show stations

**5. Screenshots (UI)**
![Screenshot from 2024-07-11 18-48-39](https://github.com/An7ar35/ctune/assets/18271866/dd36cca8-55f6-49cc-8acb-84272434f095)
**6. Configuration**

```
Resume::UUID=(null)
Resume::SourceID=0
Resume::Volume=100
IO::Plugin::Player=ffmpeg
IO::Plugin::SoundServer=pulse
IO::OverwritePlayLog=true
IO::StreamTimeout=5
IO::NetworkTimeout=8
UI::Mouse=true
UI::UnicodeIcons=false
UI::Favourites::ShowTheme=true
UI::Favourites::UseCustomTheme=false
UI::Favourites::UseLargeRows=true
UI::Favourites::SortBy=0
UI::Search::UseLargeRows=false
UI::Browser::UseLargeRows=true
UI::Theme::preset=default
UI::Theme={WHITE,BLACK}
UI::Theme::row={WHITE,BLACK}
UI::Theme::row::selected::focused={WHITE,BLUE}
UI::Theme::row::selected::unfocused={BLACK,WHITE}
UI::Theme::row::favourite::local=MAGENTA
UI::Theme::row::favourite::remote=YELLOW
UI::Theme::icon::playback::on=GREEN
UI::Theme::icon::playback::off=RED
UI::Theme::icon::queued=CYAN
UI::Theme::field::invalid=RED
UI::Theme::button={WHITE,BLACK}
UI::Theme::button::invalid=RED
UI::Theme::button::validated=GREEN

```

**7. cTune log**
The content of the error log (run `ctune --debug` to generate more granular and useful info during execution).
WHEN I RUN ctune --debug the problem fixed. I don't know if something triggered but now starts and loads everything.

**Comment by angelosne** [comment]
WHEN I RUN ctune --debug the problem fixed. I don't know if something triggered but now starts and loads everything

**Comment by An7ar35** [comment]
It was bug that occurs when 1+ of the RadioBrowser server is down or the radio station's path is not found on it any longer. v1.3.0 corrects that by trying another server until there are none left and fails gracefully after.

Thanks you for the bug report. :+1:
